# Kaggle Titanic Competition
## Titanic: Machine Learning from Disaster


***
## 1. Data Extraction
### Import Libraries

In [275]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

import keras
from keras.layers import Dense,Dropout
from keras.models import Sequential
from keras.utils.np_utils import to_categorical

### Load Data 

In [111]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

### Check data frame structure 

In [112]:
train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [113]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

***
## 2. Data Cleaning
### Check and fill missing values 

In [115]:
train.count()
test.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            332
SibSp          418
Parch          418
Ticket         418
Fare           417
Cabin           91
Embarked       418
dtype: int64

In [116]:
train["Age"] = train["Age"].fillna(train["Age"].median())
train["Embarked"] = train["Embarked"].fillna("S")
train.count()

test["Age"] = test["Age"].fillna(test["Age"].median())
test["Embarked"] = test["Embarked"].fillna("S")
test["Fare"] = test["Fare"].fillna(test["Fare"].median())
test.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            418
SibSp          418
Parch          418
Ticket         418
Fare           418
Cabin           91
Embarked       418
dtype: int64

### Convert string to numeric columns 

In [117]:
sex = {'male':0, 'female':1}
train["Sex"] = train["Sex"].map(sex)
train["Sex"].head(10)

sex = {'male':0, 'female':1}
test["Sex"] = test["Sex"].map(sex)
test["Sex"].head(10)

0    0
1    1
2    0
3    0
4    1
5    0
6    1
7    0
8    1
9    0
Name: Sex, dtype: int64

In [118]:
embarked = {'S':0, 'C':1, 'Q':2}
train["Embarked"] = train["Embarked"].map(embarked)
train["Embarked"].head(10)

embarked = {'S':0, 'C':1, 'Q':2}
test["Embarked"] = test["Embarked"].map(embarked)
test["Embarked"].head(10)

0    2
1    0
2    2
3    0
4    0
5    0
6    2
7    0
8    1
9    0
Name: Embarked, dtype: int64

***
## 3. Data Analysis
### Plotting and Visualizing Data
### Hypotheses and Assumptions

### Feature Engineering

***
## 4. Train and Evaluate the Model
### Set target, features to train model 

In [223]:
# Create the target and features numpy arrays: target, features_one
target = train["Survived"].values
#target_six = to_categorical(train["Survived"].values)

features_one = train[["Pclass", "Sex", "Age", "Fare"]].values
test_features_one = test[["Pclass", "Sex", "Age", "Fare"]].values

features_two = train[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values
test_features_two = test[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values

train_three = train.copy()
train_three["family_size"] = train_three["SibSp"] + train_three["Parch"] + 1
features_three = train_three[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "family_size"]].values
test_three = test.copy()
test_three["family_size"] = test_three["SibSp"] + test_three["Parch"] + 1
test_features_three = test_three[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "family_size"]].values

features_four = train[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values
test_features_four = test[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values

train_five = train.copy()
train_five["family_size"] = train_five["SibSp"] + train_five["Parch"] + 1
features_five = train_five[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked", "family_size"]].values
test_five = test.copy()
test_five["family_size"] = test_five["SibSp"] + test_five["Parch"] + 1
test_features_five = test_five[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked", "family_size"]].values

features_six = train[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values
test_features_six = test[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values

train.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            891
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       891
dtype: int64

### Select and train the model 

In [277]:
# Fit your first decision tree: my_tree_one
my_tree_one = tree.DecisionTreeClassifier()
my_tree_one = my_tree_one.fit(features_one, target)

my_tree_two = tree.DecisionTreeClassifier(max_depth = 10, min_samples_split = 5, random_state = 1)
my_tree_two = my_tree_two.fit(features_two, target)

my_tree_three = tree.DecisionTreeClassifier()
my_tree_three = my_tree_three.fit(features_three, target)

my_tree_four = RandomForestClassifier(max_depth=10, min_samples_split=2, n_estimators=100, random_state=1)
my_tree_four = my_tree_four.fit(features_four, target)

my_tree_five = RandomForestClassifier(max_depth=10, min_samples_split=2, n_estimators=100, random_state=1)
my_tree_five = my_tree_five.fit(features_five, target)

# Multilayer Perceptron Model
input_shape = (features_six.shape[1],)
model_six = Sequential()

model_six.add(Dense(12, activation='relu', input_dim=7))
model_six.add(Dropout(0.5))
model_six.add(Dense(64, activation='relu'))
model_six.add(Dropout(0.5))
model_six.add(Dense(1, activation='sigmoid'))

model_six.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

model_six.fit(features_six, target, epochs=500, batch_size=128)
#model_six.fit(features_six, target)#, epoch=20, validation_split=0.4) #, callbacks=[early_stopping_monitor], verbose=False)


Epoch 1/500
891/891 [==============================] - 0s - loss: 2.6858 - acc: 0.5152     
Epoch 2/500
891/891 [==============================] - 0s - loss: 2.4116 - acc: 0.5477     
Epoch 3/500
891/891 [==============================] - 0s - loss: 2.2522 - acc: 0.5511     
Epoch 4/500
891/891 [==============================] - 0s - loss: 2.0368 - acc: 0.5589     
Epoch 5/500
891/891 [==============================] - 0s - loss: 1.8477 - acc: 0.5758     
Epoch 6/500
891/891 [==============================] - 0s - loss: 1.7520 - acc: 0.5937     
Epoch 7/500
891/891 [==============================] - 0s - loss: 1.5523 - acc: 0.5926     
Epoch 8/500
891/891 [==============================] - 0s - loss: 1.4185 - acc: 0.5948     
Epoch 9/500
891/891 [==============================] - 0s - loss: 1.4046 - acc: 0.6162     
Epoch 10/500
891/891 [==============================] - 0s - loss: 1.2676 - acc: 0.5814     
Epoch 11/500
891/891 [==============================] - 0s - loss: 1.2592 - acc

891/891 [==============================] - 0s - loss: 0.6016 - acc: 0.6824     
Epoch 88/500
891/891 [==============================] - 0s - loss: 0.5810 - acc: 0.6947     
Epoch 89/500
891/891 [==============================] - 0s - loss: 0.5938 - acc: 0.6869     
Epoch 90/500
891/891 [==============================] - 0s - loss: 0.5851 - acc: 0.6925     
Epoch 91/500
891/891 [==============================] - 0s - loss: 0.5676 - acc: 0.7160     
Epoch 92/500
891/891 [==============================] - 0s - loss: 0.5861 - acc: 0.7138     
Epoch 93/500
891/891 [==============================] - 0s - loss: 0.5645 - acc: 0.7048     
Epoch 94/500
891/891 [==============================] - 0s - loss: 0.5973 - acc: 0.6970     
Epoch 95/500
891/891 [==============================] - 0s - loss: 0.5780 - acc: 0.7071     
Epoch 96/500
891/891 [==============================] - 0s - loss: 0.5671 - acc: 0.7183     
Epoch 97/500
891/891 [==============================] - 0s - loss: 0.5794 - acc: 0.

891/891 [==============================] - 0s - loss: 0.4708 - acc: 0.8070     
Epoch 175/500
891/891 [==============================] - 0s - loss: 0.4771 - acc: 0.7980     
Epoch 176/500
891/891 [==============================] - 0s - loss: 0.4710 - acc: 0.7935     
Epoch 177/500
891/891 [==============================] - 0s - loss: 0.4655 - acc: 0.7957     
Epoch 178/500
891/891 [==============================] - 0s - loss: 0.4954 - acc: 0.7811     
Epoch 179/500
891/891 [==============================] - 0s - loss: 0.4545 - acc: 0.8002     
Epoch 180/500
891/891 [==============================] - 0s - loss: 0.4538 - acc: 0.8126     
Epoch 181/500
891/891 [==============================] - 0s - loss: 0.4656 - acc: 0.8092     
Epoch 182/500
891/891 [==============================] - 0s - loss: 0.4681 - acc: 0.7935     
Epoch 183/500
891/891 [==============================] - 0s - loss: 0.4642 - acc: 0.8036     
Epoch 184/500
891/891 [==============================] - 0s - loss: 0.4525

891/891 [==============================] - 0s - loss: 0.4416 - acc: 0.8148     
Epoch 262/500
891/891 [==============================] - 0s - loss: 0.4505 - acc: 0.8159     
Epoch 263/500
891/891 [==============================] - 0s - loss: 0.4272 - acc: 0.8171     
Epoch 264/500
891/891 [==============================] - 0s - loss: 0.4245 - acc: 0.8047     
Epoch 265/500
891/891 [==============================] - 0s - loss: 0.4342 - acc: 0.8227     
Epoch 266/500
891/891 [==============================] - 0s - loss: 0.4322 - acc: 0.8249     
Epoch 267/500
891/891 [==============================] - 0s - loss: 0.4301 - acc: 0.8159     
Epoch 268/500
891/891 [==============================] - 0s - loss: 0.4175 - acc: 0.8215     
Epoch 269/500
891/891 [==============================] - 0s - loss: 0.4262 - acc: 0.8215     
Epoch 270/500
891/891 [==============================] - 0s - loss: 0.4268 - acc: 0.8193     
Epoch 271/500
891/891 [==============================] - 0s - loss: 0.4270

891/891 [==============================] - 0s - loss: 0.4044 - acc: 0.8249     
Epoch 348/500
891/891 [==============================] - 0s - loss: 0.4065 - acc: 0.8361     
Epoch 349/500
891/891 [==============================] - 0s - loss: 0.4096 - acc: 0.8260     
Epoch 350/500
891/891 [==============================] - 0s - loss: 0.4203 - acc: 0.8238     
Epoch 351/500
891/891 [==============================] - 0s - loss: 0.4250 - acc: 0.8249     
Epoch 352/500
891/891 [==============================] - 0s - loss: 0.4083 - acc: 0.8328     
Epoch 353/500
891/891 [==============================] - 0s - loss: 0.4090 - acc: 0.8294     
Epoch 354/500
891/891 [==============================] - 0s - loss: 0.4294 - acc: 0.8294     
Epoch 355/500
891/891 [==============================] - 0s - loss: 0.3987 - acc: 0.8294     
Epoch 356/500
891/891 [==============================] - 0s - loss: 0.4000 - acc: 0.8384     
Epoch 357/500
891/891 [==============================] - 0s - loss: 0.4211

891/891 [==============================] - 0s - loss: 0.4108 - acc: 0.8215     
Epoch 435/500
891/891 [==============================] - 0s - loss: 0.4123 - acc: 0.8249     
Epoch 436/500
891/891 [==============================] - 0s - loss: 0.4155 - acc: 0.8238     
Epoch 437/500
891/891 [==============================] - 0s - loss: 0.4111 - acc: 0.8339     
Epoch 438/500
891/891 [==============================] - 0s - loss: 0.4094 - acc: 0.8440     
Epoch 439/500
891/891 [==============================] - 0s - loss: 0.4253 - acc: 0.8272     
Epoch 440/500
891/891 [==============================] - 0s - loss: 0.4262 - acc: 0.8260     
Epoch 441/500
891/891 [==============================] - 0s - loss: 0.4070 - acc: 0.8350     
Epoch 442/500
891/891 [==============================] - 0s - loss: 0.4050 - acc: 0.8395     
Epoch 443/500
891/891 [==============================] - 0s - loss: 0.4048 - acc: 0.8373     
Epoch 444/500
891/891 [==============================] - 0s - loss: 0.4039

### Performance evaluation 

In [278]:
# Look at the importance and score of the included features
print(my_tree_one.feature_importances_)
print(my_tree_one.score(features_one, target))

print(my_tree_two.feature_importances_)
print(my_tree_two.score(features_two, target))

print(my_tree_three.feature_importances_)
print(my_tree_three.score(features_three, target))

print(my_tree_four.feature_importances_)
print(my_tree_four.score(features_four, target))

print(my_tree_five.feature_importances_)
print(my_tree_five.score(features_five, target))

[ 0.12315342  0.31274009  0.24940626  0.31470023]
0.977553310887
[ 0.14130255  0.17906027  0.41616727  0.17938711  0.05039699  0.01923751
  0.0144483 ]
0.905723905724
[ 0.10681611  0.31088095  0.22717985  0.26491993  0.01318868  0.01739451
  0.05961997]
0.979797979798
[ 0.10384741  0.20139027  0.31989322  0.24602858  0.05272693  0.04159232
  0.03452128]
0.939393939394
[ 0.09915728  0.31168455  0.20147389  0.22532166  0.03731813  0.03178077
  0.03580558  0.05745814]
0.938271604938


In [280]:
score = model_six.evaluate(features_six, target, batch_size=128)

128/891 [===>..........................] - ETA: 0s

***
## 5. Predict the Test set

### Select test model features 

In [231]:
test.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            418
SibSp          418
Parch          418
Ticket         418
Fare           418
Cabin           91
Embarked       418
dtype: int64

### Make predictions 

In [284]:
# Make your prediction using the test set
my_prediction = my_tree_one.predict(test_features).reshape((418,1))
my_prediction.shape

my_prediction_two = my_tree_two.predict(test_features_two).reshape((418,1))
my_prediction_two.shape

my_prediction_three = my_tree_three.predict(test_features_three).reshape((418,1))
my_prediction_three.shape

my_prediction_four = my_tree_four.predict(test_features_four).reshape((418,1))
my_prediction_four.shape

my_prediction_five = my_tree_five.predict(test_features_five).reshape((418,1))
my_prediction_five.shape

my_prediction_six = model_six.predict(test_features_six)
my_prediction_six.view()
#.reshape(418,2)
#my_prediction_six = my_prediction_six[:,0]
#my_prediction_six = (my_prediction_six < 0.5).astype(int)

array([[  3.30899283e-02],
       [  2.94427633e-01],
       [  7.23309407e-04],
       [  1.16859801e-01],
       [  3.55024397e-01],
       [  1.60863131e-01],
       [  6.95835888e-01],
       [  1.51664749e-01],
       [  6.68886781e-01],
       [  1.06849693e-01],
       [  1.16782524e-01],
       [  3.48885238e-01],
       [  9.83466685e-01],
       [  1.70872971e-01],
       [  9.84844267e-01],
       [  9.16520000e-01],
       [  1.87797338e-01],
       [  1.69497088e-01],
       [  2.65213460e-01],
       [  3.37423712e-01],
       [  3.54308188e-01],
       [  3.37859720e-01],
       [  9.85214531e-01],
       [  3.95425886e-01],
       [  8.71451259e-01],
       [  8.09467286e-02],
       [  9.83853698e-01],
       [  1.60154670e-01],
       [  3.59612882e-01],
       [  1.27752811e-01],
       [  1.54426306e-01],
       [  1.31528243e-01],
       [  3.07075441e-01],
       [  3.50460768e-01],
       [  3.84458303e-01],
       [  1.85840219e-01],
       [  4.51461494e-01],
 

***
## 6. Save Results
### Create the Solution 

In [273]:
my_solution = pd.DataFrame(my_prediction_six, test["PassengerId"], columns = ["Survived"])
my_solution.index.name

'PassengerId'

### Save to CSV file 

In [274]:
my_solution.to_csv("my_solution_six.csv")

***
***
# Rough Work 

In [17]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized exec time: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For-loop exec time: " + str(1000*(toc-tic)) + "ms")

249972.075277
Vectorized exec time: 1.5177726745605469ms
249972.075277
For-loop exec time: 624.934196472168ms


In [18]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [19]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [20]:
cal.reshape(1,4)

array([[  59. ,  239. ,  155.4,   76.9]])

In [22]:
p = 100*A/cal
print(p)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [27]:
B=np.array([1,2,3,4])

In [28]:
print(B)

[1 2 3 4]


In [29]:
print(B.T)

[1 2 3 4]


In [38]:
B


array([1, 2, 3, 4])

In [37]:
B.T

array([1, 2, 3, 4])

In [36]:
B.shape

(4,)

In [34]:
B.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [39]:
B

array([1, 2, 3, 4])

In [40]:
B=B.reshape(4,1
           )

In [45]:
B

array([[1],
       [2],
       [3],
       [4]])

In [42]:
B.shape

(4, 1)

In [43]:
B.T


array([[1, 2, 3, 4]])

In [44]:
%matplotlib inline