# Kaggle Titanic Competition
## Titanic: Machine Learning from Disaster


***
## 1. Data Extraction
### Import Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

import keras
from keras.layers import Dense,Dropout
from keras.models import Sequential
from keras.utils.np_utils import to_categorical

Using TensorFlow backend.


### Load Data 

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

### Check data frame structure 

In [3]:
train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [4]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

***
## 2. Data Cleaning
### Check and fill missing values 

In [5]:
train.count()
test.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            332
SibSp          418
Parch          418
Ticket         418
Fare           417
Cabin           91
Embarked       418
dtype: int64

In [6]:
train["Age"] = train["Age"].fillna(train["Age"].median())
train["Embarked"] = train["Embarked"].fillna("S")
train.count()

test["Age"] = test["Age"].fillna(test["Age"].median())
test["Embarked"] = test["Embarked"].fillna("S")
test["Fare"] = test["Fare"].fillna(test["Fare"].median())
test.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            418
SibSp          418
Parch          418
Ticket         418
Fare           418
Cabin           91
Embarked       418
dtype: int64

### Convert string to numeric columns 

In [7]:
sex = {'male':0, 'female':1}
train["Sex"] = train["Sex"].map(sex)
train["Sex"].head(10)

sex = {'male':0, 'female':1}
test["Sex"] = test["Sex"].map(sex)
test["Sex"].head(10)

0    0
1    1
2    0
3    0
4    1
5    0
6    1
7    0
8    1
9    0
Name: Sex, dtype: int64

In [8]:
embarked = {'S':0, 'C':1, 'Q':2}
train["Embarked"] = train["Embarked"].map(embarked)
train["Embarked"].head(10)

embarked = {'S':0, 'C':1, 'Q':2}
test["Embarked"] = test["Embarked"].map(embarked)
test["Embarked"].head(10)

0    2
1    0
2    2
3    0
4    0
5    0
6    2
7    0
8    1
9    0
Name: Embarked, dtype: int64

***
## 3. Data Analysis
### Plotting and Visualizing Data
### Hypotheses and Assumptions

### Feature Engineering

***
## 4. Train and Evaluate the Model
### Set target, features to train model 

In [9]:
# Create the target and features numpy arrays: target, features_one
target = train["Survived"].values
#target_six = to_categorical(train["Survived"].values)

features_one = train[["Pclass", "Sex", "Age", "Fare"]].values
test_features_one = test[["Pclass", "Sex", "Age", "Fare"]].values

features_two = train[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values
test_features_two = test[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values

train_three = train.copy()
train_three["family_size"] = train_three["SibSp"] + train_three["Parch"] + 1
features_three = train_three[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "family_size"]].values
test_three = test.copy()
test_three["family_size"] = test_three["SibSp"] + test_three["Parch"] + 1
test_features_three = test_three[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "family_size"]].values

features_four = train[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values
test_features_four = test[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values

train_five = train.copy()
train_five["family_size"] = train_five["SibSp"] + train_five["Parch"] + 1
features_five = train_five[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked", "family_size"]].values
test_five = test.copy()
test_five["family_size"] = test_five["SibSp"] + test_five["Parch"] + 1
test_features_five = test_five[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "Embarked", "family_size"]].values

features_six = train[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values
test_features_six = test[["Pclass","Age","Sex","Fare", "SibSp", "Parch", "Embarked"]].values

train.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            891
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       891
dtype: int64

### Select and train the model 

In [10]:
# Fit your first decision tree: my_tree_one
my_tree_one = tree.DecisionTreeClassifier()
my_tree_one = my_tree_one.fit(features_one, target)

my_tree_two = tree.DecisionTreeClassifier(max_depth = 10, min_samples_split = 5, random_state = 1)
my_tree_two = my_tree_two.fit(features_two, target)

my_tree_three = tree.DecisionTreeClassifier()
my_tree_three = my_tree_three.fit(features_three, target)

my_tree_four = RandomForestClassifier(max_depth=10, min_samples_split=2, n_estimators=100, random_state=1)
my_tree_four = my_tree_four.fit(features_four, target)

my_tree_five = RandomForestClassifier(max_depth=10, min_samples_split=2, n_estimators=100, random_state=1)
my_tree_five = my_tree_five.fit(features_five, target)

# Multilayer Perceptron Model
input_shape = (features_six.shape[1],)
model_six = Sequential()

model_six.add(Dense(12, activation='relu', input_dim=7))
model_six.add(Dropout(0.5))
model_six.add(Dense(64, activation='relu'))
model_six.add(Dropout(0.5))
model_six.add(Dense(1, activation='sigmoid'))

model_six.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

model_six.fit(features_six, target, epochs=500, batch_size=128)
#model_six.fit(features_six, target)#, epoch=20, validation_split=0.4) #, callbacks=[early_stopping_monitor], verbose=False)


Epoch 1/500
891/891 [==============================] - 1s - loss: 2.6583 - acc: 0.5253     
Epoch 2/500
891/891 [==============================] - 0s - loss: 2.7655 - acc: 0.5578     
Epoch 3/500
891/891 [==============================] - 0s - loss: 2.7688 - acc: 0.5634     
Epoch 4/500
891/891 [==============================] - 0s - loss: 2.2365 - acc: 0.5657     
Epoch 5/500
891/891 [==============================] - 0s - loss: 2.1200 - acc: 0.5847     
Epoch 6/500
891/891 [==============================] - 0s - loss: 2.1433 - acc: 0.5612     
Epoch 7/500
891/891 [==============================] - 0s - loss: 2.0271 - acc: 0.5859     
Epoch 8/500
891/891 [==============================] - 0s - loss: 2.0563 - acc: 0.5825     
Epoch 9/500
891/891 [==============================] - 0s - loss: 1.7638 - acc: 0.5993     
Epoch 10/500
891/891 [==============================] - 0s - loss: 1.8579 - acc: 0.5791     
Epoch 11/500
891/891 [==============================] - 0s - loss: 1.9416 - acc

891/891 [==============================] - 0s - loss: 0.6027 - acc: 0.6364     
Epoch 90/500
891/891 [==============================] - 0s - loss: 0.5979 - acc: 0.6566     
Epoch 91/500
891/891 [==============================] - 0s - loss: 0.5998 - acc: 0.6453     
Epoch 92/500
891/891 [==============================] - 0s - loss: 0.5943 - acc: 0.6498     
Epoch 93/500
891/891 [==============================] - 0s - loss: 0.6007 - acc: 0.6465     
Epoch 94/500
891/891 [==============================] - 0s - loss: 0.6040 - acc: 0.6420     
Epoch 95/500
891/891 [==============================] - 0s - loss: 0.5941 - acc: 0.6465     
Epoch 96/500
891/891 [==============================] - 0s - loss: 0.6103 - acc: 0.6386     
Epoch 97/500
891/891 [==============================] - 0s - loss: 0.6058 - acc: 0.6319     
Epoch 98/500
891/891 [==============================] - 0s - loss: 0.5983 - acc: 0.6431     
Epoch 99/500
891/891 [==============================] - 0s - loss: 0.5816 - acc: 0.

891/891 [==============================] - 0s - loss: 0.5778 - acc: 0.6936     
Epoch 176/500
891/891 [==============================] - 0s - loss: 0.5777 - acc: 0.6521     
Epoch 177/500
891/891 [==============================] - 0s - loss: 0.5671 - acc: 0.6846     
Epoch 178/500
891/891 [==============================] - 0s - loss: 0.5579 - acc: 0.7015     
Epoch 179/500
891/891 [==============================] - 0s - loss: 0.5664 - acc: 0.6958     
Epoch 180/500
891/891 [==============================] - 0s - loss: 0.5627 - acc: 0.6925     
Epoch 181/500
891/891 [==============================] - 0s - loss: 0.5757 - acc: 0.6667     
Epoch 182/500
891/891 [==============================] - 0s - loss: 0.5708 - acc: 0.6869     
Epoch 183/500
891/891 [==============================] - 0s - loss: 0.5660 - acc: 0.6947     
Epoch 184/500
891/891 [==============================] - 0s - loss: 0.5912 - acc: 0.6768     
Epoch 185/500
891/891 [==============================] - 0s - loss: 0.5660

891/891 [==============================] - 0s - loss: 0.5478 - acc: 0.7194     
Epoch 262/500
891/891 [==============================] - 0s - loss: 0.5551 - acc: 0.7026     
Epoch 263/500
891/891 [==============================] - 0s - loss: 0.5663 - acc: 0.7217     
Epoch 264/500
891/891 [==============================] - 0s - loss: 0.5787 - acc: 0.6846     
Epoch 265/500
891/891 [==============================] - 0s - loss: 0.5595 - acc: 0.7015     
Epoch 266/500
891/891 [==============================] - 0s - loss: 0.5566 - acc: 0.7149     
Epoch 267/500
891/891 [==============================] - 0s - loss: 0.5608 - acc: 0.7284     
Epoch 268/500
891/891 [==============================] - 0s - loss: 0.5680 - acc: 0.7003     
Epoch 269/500
891/891 [==============================] - 0s - loss: 0.5578 - acc: 0.7116     
Epoch 270/500
891/891 [==============================] - 0s - loss: 0.5611 - acc: 0.7183     
Epoch 271/500
891/891 [==============================] - 0s - loss: 0.5616

891/891 [==============================] - ETA: 0s - loss: 0.6112 - acc: 0.664 - 0s - loss: 0.5412 - acc: 0.7340     
Epoch 348/500
891/891 [==============================] - 0s - loss: 0.5540 - acc: 0.7205     
Epoch 349/500
891/891 [==============================] - 0s - loss: 0.5479 - acc: 0.7396     
Epoch 350/500
891/891 [==============================] - 0s - loss: 0.5588 - acc: 0.7172     
Epoch 351/500
891/891 [==============================] - 0s - loss: 0.5464 - acc: 0.7452     
Epoch 352/500
891/891 [==============================] - 0s - loss: 0.5427 - acc: 0.7396     
Epoch 353/500
891/891 [==============================] - 0s - loss: 0.5481 - acc: 0.7250     
Epoch 354/500
891/891 [==============================] - 0s - loss: 0.5551 - acc: 0.7217     
Epoch 355/500
891/891 [==============================] - 0s - loss: 0.5435 - acc: 0.7318     
Epoch 356/500
891/891 [==============================] - 0s - loss: 0.5465 - acc: 0.7318     
Epoch 357/500
891/891 [=============

891/891 [==============================] - 0s - loss: 0.5343 - acc: 0.7565     
Epoch 434/500
891/891 [==============================] - 0s - loss: 0.5270 - acc: 0.7497     
Epoch 435/500
891/891 [==============================] - 0s - loss: 0.5370 - acc: 0.7486     
Epoch 436/500
891/891 [==============================] - 0s - loss: 0.5139 - acc: 0.7677     
Epoch 437/500
891/891 [==============================] - 0s - loss: 0.5119 - acc: 0.7677     
Epoch 438/500
891/891 [==============================] - 0s - loss: 0.5298 - acc: 0.7452     
Epoch 439/500
891/891 [==============================] - 0s - loss: 0.5224 - acc: 0.7565     
Epoch 440/500
891/891 [==============================] - 0s - loss: 0.5382 - acc: 0.7542     
Epoch 441/500
891/891 [==============================] - 0s - loss: 0.5239 - acc: 0.7688     
Epoch 442/500
891/891 [==============================] - 0s - loss: 0.5264 - acc: 0.7587     
Epoch 443/500
891/891 [==============================] - 0s - loss: 0.5267

### Performance evaluation 

In [12]:
# Look at the importance and score of the included features
print(my_tree_one.feature_importances_)
print(my_tree_one.score(features_one, target))

print(my_tree_two.feature_importances_)
print(my_tree_two.score(features_two, target))

print(my_tree_three.feature_importances_)
print(my_tree_three.score(features_three, target))

print(my_tree_four.feature_importances_)
print(my_tree_four.score(features_four, target))

print(my_tree_five.feature_importances_)
print(my_tree_five.score(features_five, target))

[ 0.1269655   0.31274009  0.24356945  0.31672496]
0.977553310887
[ 0.14130255  0.17906027  0.41616727  0.17938711  0.05039699  0.01923751
  0.0144483 ]
0.905723905724
[ 0.10681611  0.31088095  0.24111194  0.25747731  0.00754539  0.01793795
  0.05823035]
0.979797979798
[ 0.10384741  0.20139027  0.31989322  0.24602858  0.05272693  0.04159232
  0.03452128]
0.939393939394
[ 0.09915728  0.31168455  0.20147389  0.22532166  0.03731813  0.03178077
  0.03580558  0.05745814]
0.938271604938


In [13]:
score = model_six.evaluate(features_six, target, batch_size=128)

128/891 [===>..........................] - ETA: 1s

***
## 5. Predict the Test set

### Select test model features 

In [14]:
test.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            418
SibSp          418
Parch          418
Ticket         418
Fare           418
Cabin           91
Embarked       418
dtype: int64

### Make predictions 

In [15]:
# Make your prediction using the test set
my_prediction = my_tree_one.predict(test_features).reshape((418,1))
my_prediction.shape

my_prediction_two = my_tree_two.predict(test_features_two).reshape((418,1))
my_prediction_two.shape

my_prediction_three = my_tree_three.predict(test_features_three).reshape((418,1))
my_prediction_three.shape

my_prediction_four = my_tree_four.predict(test_features_four).reshape((418,1))
my_prediction_four.shape

my_prediction_five = my_tree_five.predict(test_features_five).reshape((418,1))
my_prediction_five.shape

my_prediction_six = model_six.predict(test_features_six)
my_prediction_six.view()
#.reshape(418,2)
#my_prediction_six = my_prediction_six[:,0]
#my_prediction_six = (my_prediction_six < 0.5).astype(int)

NameError: name 'test_features' is not defined

***
## 6. Save Results
### Create the Solution 

In [16]:
my_solution = pd.DataFrame(my_prediction_six, test["PassengerId"], columns = ["Survived"])
my_solution.index.name

NameError: name 'my_prediction_six' is not defined

### Save to CSV file 

In [274]:
my_solution.to_csv("my_solution_six.csv")

***
***
# Rough Work 

In [17]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized exec time: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For-loop exec time: " + str(1000*(toc-tic)) + "ms")

249972.075277
Vectorized exec time: 1.5177726745605469ms
249972.075277
For-loop exec time: 624.934196472168ms


In [18]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [19]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [20]:
cal.reshape(1,4)

array([[  59. ,  239. ,  155.4,   76.9]])

In [22]:
p = 100*A/cal
print(p)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [27]:
B=np.array([1,2,3,4])

In [28]:
print(B)

[1 2 3 4]


In [29]:
print(B.T)

[1 2 3 4]


In [38]:
B


array([1, 2, 3, 4])

In [37]:
B.T

array([1, 2, 3, 4])

In [36]:
B.shape

(4,)

In [34]:
B.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [39]:
B

array([1, 2, 3, 4])

In [40]:
B=B.reshape(4,1
           )

In [45]:
B

array([[1],
       [2],
       [3],
       [4]])

In [42]:
B.shape

(4, 1)

In [43]:
B.T


array([[1, 2, 3, 4]])

In [44]:
%matplotlib inline